ALTER TABLE "organizations" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employee_addresses" ALTER COLUMN "address_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "gender" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "employment_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "billing_cycle" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "work_unit" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "employee_onboarding_invites" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "holiday_template_assignments" ALTER COLUMN "assignment_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "shift_breaks" ALTER COLUMN "category" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "shift_breaks" ALTER COLUMN "pay_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "shift_breaks" ALTER COLUMN "rule_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "shift_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "attendance_events" ALTER COLUMN "event_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "attendance_records" ALTER COLUMN "attendance_status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "attendance_records" ALTER COLUMN "attendance_source" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "leave_approvals" ALTER COLUMN "decision" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "leave_policy_approval_approvers" ALTER COLUMN "approver_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "leave_policy_template_assignments" ALTER COLUMN "assignment_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "leave_policy_template_items" ALTER COLUMN "accrual_period" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "leave_policy_templates" ALTER COLUMN "policy_cycle" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "leave_requests" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "payroll_adjustments" ALTER COLUMN "adjustment_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "payroll_cycles" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "payroll_runs" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "payslips" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "salary_components" ALTER COLUMN "component_type" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "integration_configs" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "webhook_logs" ALTER COLUMN "status" SET DATA TYPE varchar(60);--> statement-breakpoint
ALTER TABLE "platform_admins" ALTER COLUMN "status" SET DATA TYPE varchar(60);