/** India states + cities for onboarding reference APIs (curated lists; expand as needed). */

export const INDIAN_STATES = [
  { code: "AP", name: "Andhra Pradesh" },
  { code: "AR", name: "Arunachal Pradesh" },
  { code: "AS", name: "Assam" },
  { code: "BR", name: "Bihar" },
  { code: "CG", name: "Chhattisgarh" },
  { code: "GA", name: "Goa" },
  { code: "GJ", name: "Gujarat" },
  { code: "HR", name: "Haryana" },
  { code: "HP", name: "Himachal Pradesh" },
  { code: "JH", name: "Jharkhand" },
  { code: "KA", name: "Karnataka" },
  { code: "KL", name: "Kerala" },
  { code: "MP", name: "Madhya Pradesh" },
  { code: "MH", name: "Maharashtra" },
  { code: "MN", name: "Manipur" },
  { code: "ML", name: "Meghalaya" },
  { code: "MZ", name: "Mizoram" },
  { code: "NL", name: "Nagaland" },
  { code: "OD", name: "Odisha" },
  { code: "PB", name: "Punjab" },
  { code: "RJ", name: "Rajasthan" },
  { code: "SK", name: "Sikkim" },
  { code: "TN", name: "Tamil Nadu" },
  { code: "TS", name: "Telangana" },
  { code: "TR", name: "Tripura" },
  { code: "UP", name: "Uttar Pradesh" },
  { code: "UK", name: "Uttarakhand" },
  { code: "WB", name: "West Bengal" },
  { code: "AN", name: "Andaman and Nicobar Islands" },
  { code: "CH", name: "Chandigarh" },
  { code: "DN", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { code: "DL", name: "Delhi" },
  { code: "JK", name: "Jammu and Kashmir" },
  { code: "LA", name: "Ladakh" },
  { code: "LD", name: "Lakshadweep" },
  { code: "PY", name: "Puducherry" },
] as const;

const CITIES_BY_CODE: Record<string, readonly string[]> = {
  AP: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kurnool", "Rajahmundry", "Kadapa", "Anantapur", "Eluru", "Ongole", "Chittoor", "Machilipatnam", "Hindupur", "Nandyal", "Tenali", "Proddatur", "Adoni", "Amaravati", "Bhimavaram"],
  AR: ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Along", "Tezu", "Bomdila", "Khonsa", "Aalo"],
  AS: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon", "Dhubri", "Goalpara", "Karimganj", "Lakhimpur", "Sivasagar", "Haflong", "Dhemaji"],
  BR: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Arrah", "Begusarai", "Katihar", "Munger", "Chapra", "Sasaram", "Hajipur", "Siwan", "Motihari", "Bettiah", "Saharsa", "Sitamarhi", "Jehanabad", "Nawada"],
  CG: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Rajnandgaon", "Raigarh", "Jagdalpur", "Ambikapur", "Durg", "Mahasamund", "Dhamtari", "Janjgir", "Kanker", "Kawardha", "Mungeli"],
  GA: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim", "Valpoi", "Canacona", "Curchorem", "Pernem"],
  GJ: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Junagadh", "Gandhinagar", "Anand", "Nadiad", "Morbi", "Bharuch", "Mehsana", "Surendranagar", "Navsari", "Valsad", "Bhuj", "Godhra", "Palanpur", "Porbandar"],
  HR: ["Faridabad", "Gurugram", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula", "Bhiwani", "Sirsa", "Bahadurgarh", "Jind", "Kaithal", "Rewari", "Palwal", "Thanesar", "Fatehabad", "Narnaul"],
  HP: ["Shimla", "Dharamshala", "Solan", "Mandi", "Palampur", "Baddi", "Kullu", "Manali", "Chamba", "Una", "Hamirpur", "Nahan", "Bilaspur", "Kangra", "Nurpur"],
  JH: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Phusro", "Hazaribagh", "Giridih", "Ramgarh", "Medininagar", "Chaibasa", "Dumka", "Gumla", "Lohardaga", "Pakur"],
  KA: ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi", "Kalaburagi", "Davanagere", "Ballari", "Shivamogga", "Tumakuru", "Raichur", "Bidar", "Hassan", "Udupi", "Chikkamagaluru", "Mandya", "Kolar", "Ramanagara", "Chitradurga", "Gadag", "Haveri", "Bagalkot", "Vijayapura", "Karwar", "Madikeri", "Chikkaballapur", "Yadgir", "Koppal", "Sirsi", "Puttur"],
  KL: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Alappuzha", "Palakkad", "Malappuram", "Kannur", "Kasaragod", "Pathanamthitta", "Idukki", "Wayanad", "Vatakara", "Kanhangad"],
  MP: ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar", "Ratlam", "Dewas", "Satna", "Rewa", "Murwara", "Singrauli", "Burhanpur", "Khandwa", "Chhindwara", "Morena", "Bhind", "Guna", "Shivpuri", "Mandsaur"],
  MH: ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Amravati", "Kolhapur", "Sangli", "Malegaon", "Jalgaon", "Akola", "Latur", "Dhule", "Ahmednagar", "Chandrapur", "Parbhani", "Ichalkaranji", "Jalna", "Bhusawal", "Panvel", "Satara", "Beed", "Yavatmal", "Ratnagiri", "Gondia", "Wardha", "Achalpur", "Osmanabad"],
  MN: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul", "Senapati", "Tamenglong", "Kakching"],
  ML: ["Shillong", "Tura", "Jowai", "Nongpoh", "Williamnagar", "Baghmara", "Mairang"],
  MZ: ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Lawngtlai", "Saiha", "Kolasib", "Mamit"],
  NL: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Phek", "Mon"],
  OD: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda", "Rayagada", "Jeypore", "Angul", "Dhenkanal", "Paradip"],
  PB: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Pathankot", "Hoshiarpur", "Mohali", "Batala", "Moga", "Abohar", "Malerkotla", "Khanna", "Phagwara", "Muktsar", "Firozpur", "Barnala", "Sangrur", "Rupnagar", "Fazilka"],
  RJ: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Bharatpur", "Sikar", "Pali", "Tonk", "Sriganganagar", "Hanumangarh", "Churu", "Nagaur", "Barmer", "Jaisalmer", "Dungarpur", "Banswara"],
  SK: ["Gangtok", "Namchi", "Mangan", "Gyalshing", "Ravangla", "Jorethang"],
  TN: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur", "Erode", "Vellore", "Thoothukudi", "Dindigul", "Thanjavur", "Ranipet", "Nagercoil", "Kanchipuram", "Karur", "Hosur", "Neyveli", "Ooty", "Cuddalore", "Kumbakonam", "Sivakasi", "Rajapalayam", "Ambur", "Krishnagiri", "Nagapattinam"],
  TS: ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar", "Ramagundam", "Mahbubnagar", "Nalgonda", "Adilabad", "Siddipet", "Miryalaguda", "Jagtial", "Suryapet", "Kamareddy", "Mancherial"],
  TR: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Belonia", "Kumarghat", "Ambassa"],
  UP: ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Prayagraj", "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Noida", "Firozabad", "Jhansi", "Muzaffarnagar", "Mathura", "Rampur", "Shahjahanpur", "Farrukhabad", "Ayodhya", "Bahraich", "Modinagar", "Unnao", "Jaunpur", "Mirzapur", "Etawah", "Bulandshahr", "Sitapur", "Hardoi"],
  UK: ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Kashipur", "Rishikesh", "Pithoragarh", "Almora", "Nainital", "Chamoli", "Kotdwar", "Tehri", "Pauri"],
  WB: ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Malda", "Bardhaman", "Kharagpur", "Haldia", "Baharampur", "Raiganj", "Jalpaiguri", "Balurghat", "Bankura", "Purulia", "Krishnanagar", "English Bazar", "Cooch Behar", "Alipurduar", "Darjeeling"],
  AN: ["Port Blair", "Diglipur", "Mayabunder", "Rangat", "Car Nicobar"],
  CH: ["Chandigarh"],
  DN: ["Daman", "Diu", "Silvassa", "Naroli"],
  DL: ["New Delhi", "Delhi", "Dwarka", "Rohini", "Janakpuri", "Pitampura", "Vasant Kunj", "Karol Bagh"],
  JK: ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur", "Kathua", "Pulwama", "Rajouri", "Poonch", "Kupwara"],
  LA: ["Leh", "Kargil"],
  LD: ["Kavaratti", "Agatti", "Minicoy", "Amini"],
  PY: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
};

export function listCitiesForState(stateCode: string): string[] {
  const k = stateCode.toUpperCase();
  const row = CITIES_BY_CODE[k];
  return row ? [...row] : [];
}
